language: bash
services: docker

env:
  - VERSION=3.7-rc VARIANT=debian
  - VERSION=3.7-rc VARIANT=alpine
  - VERSION=3.6 VARIANT=debian
  - VERSION=3.6 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="rabbitmq:$VERSION-$VARIANT"

script:
  - travis_retry docker build -t "$image" "$VARIANT"
  - ~/official-images/test/run.sh "$image"
  - travis_retry docker build -t "${image}-management" "$VARIANT/management"
  - ~/official-images/test/run.sh "${image}-management"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
